Approve AToken once
pooltogether/aave-yield-source pull request #21
Opened 2021-06-29 22:08 UTC by aodhgan

2021-06-30 08:11 UTC, PierrickGT requested changes

2021-06-30 08:11 UTC, PierrickGT commented on test/ATokenYieldSource.test.ts
> +    await underlyingToken.mock.safeApprove.returns(true);
To mock `safeApprove`, you actually need to mock `approve`, so something like:
```suggestion
    await underlyingToken.mock.approve.withArgs(lendingPoolAddress, maxAmount).returns(true);
```

2021-07-05 13:40 UTC, PierrickGT approved these changes

2021-07-05 23:50 UTC, asselstine requested changes
We also need a function to re-approve the max amount, in case for whatever reason the approval level drops too low.

2021-07-06 14:43 UTC, PierrickGT commented
> We also need a function to re-approve the max amount, in case for whatever reason the approval level drops too low.

@asselstine added in this commit: https://github.com/pooltogether/aave-yield-source/pull/21/commits/efe08df871f5437f5a9899a6617b188fc7d355f7

2021-07-06 16:10 UTC, asselstine approved these changes
...with a test!  Good job.

2021-07-06 16:36 UTC, merged