Updated yield source to use constructor, Manageable, and solidity 0.8.6
pooltogether/aave-yield-source pull request #27
Opened 2021-10-12 22:14 UTC by asselstine

2021-10-12 22:40 UTC, PierrickGT requested changes

2021-10-12 22:40 UTC, PierrickGT commented on .solhint.json
> +      "compiler-version": ["error", "^0.8.6"],
```suggestion
      "compiler-version": ["error", "0.8.6"],
```

2021-10-12 22:40 UTC, PierrickGT commented on contracts/test/SafeERC20WrapperUpgradeable.sol
> +// https://github.com/OpenZeppelin/openzeppelin-contracts-/blob/master/contracts/mocks/SafeERC20Helper.sol
We should also rename the contract to `SafeERC20Wrapper.sol`.

2021-10-12 22:40 UTC, PierrickGT commented on contracts/yield-source/ATokenYieldSource.sol
> +  function decimals() public override view returns (uint8) {
Add Natspec doc.

2021-10-12 22:40 UTC, PierrickGT commented on contracts/yield-source/ATokenYieldSource.sol
> +  function balanceOfToken(address addr) external override view returns (uint256) {
`balanceOfToken` is `external` in the Yield Source Interface so we can't use `view`.
https://github.com/pooltogether/yield-source-interface/blob/27a2118c2f7265786284684929346a77f5cab9b6/contracts/IYieldSource.sol#L14

2021-10-12 22:40 UTC, PierrickGT commented on hardhat.config.ts
> -    },
We will need these for the deployment.

2021-10-13 18:41 UTC, asselstine commented on contracts/yield-source/ATokenYieldSource.sol
> +  function balanceOfToken(address addr) external override view returns (uint256) {
This is a funny one...because the compiler doesn't complain.  I wonder if this is okay?

2021-10-13 18:41 UTC, asselstine commented on hardhat.config.ts
> -    },
Deployment happens in `v4-mainnet` !

2021-10-13 18:49 UTC, merged